### ISSUE TITLE
D&D-Upload funktioniert nicht mit WB 2.12.1

### ISSUE THREAD

**Issue by instantflorian** [WBCE/News-with-Images#44]
![2019-05-22_071550](https://user-images.githubusercontent.com/1433754/58149021-75b55200-7c61-11e9-8c9a-9481f2eb83b4.jpg)

**Comment by instantflorian** [comment]
...Upload-Versuch führt zudem beim Speichern zu einer Sicherheitsverletzung™
![2019-05-22_071636](https://user-images.githubusercontent.com/1433754/58149111-cc229080-7c61-11e9-9fc1-57ab1955dba6.jpg)

SiVe tritt nur beim Versuch des Uploads von Galeriebildern auf, nicht bei Posts ohne Bilder

**Comment by mrbaseman** [comment]
for the JSON syntax errors: have a look into the server's error log, if there are any notices or errors that disturb the JSON output when they are also sent to the browser.

The FTAN error, however, could be difficult to fix for WB. In WB 2.8.3 it was a nightmare to get it working correctly, but the single tab mode has always caused trouble for the users. WBCE we have a patch to handle this better, but WB has addressed that problem in a different manner, so that it has become even more complicated nowadays to handle FTANs correctly for both platforms. It's not impossible (mpForm and OPF Dashboard both use FTANs and least mpForm is heavily used in both communities).  I'll have a look.

**Comment by mrbaseman** [comment]
Obiger commit repariert die Probleme mit IDKEYs. In meinen Tests unter WB 2.12 hat damit der Upload von Bildern funktioniert. Ich weiß nicht ob wir mit FTANs noch ein Problem haben. Vielleicht war das ein Folgefehler. Auch den Syntax Error im JSON sehe ich in meiner Umgebung nicht. @instantflorian kannst du bitte nochmal testen?
